---

#########################################################
## Podman Create Pod module                            ##
#########################################################
# Validate global variables.
- name: Validate variables for Podman Pod module...
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - container_repository_url
    - container_name
    - container_pod

##################################
# Create podman pod              #
##################################

# Create Podman pod quadlet to isolate one or more containers in running environment
- name: "Create Podman Pod with name {{ container_pod | splitext | first }}..."
  become: true
  become_user: "{{ podman_service_user }}"
  containers.podman.podman_pod:
    name: "{{ container_pod | splitext | first }}"
    state: quadlet
    network: "{{ container_network }}"
    ports: "{{ container_pod_ports | default(omit) }}"
    publish: "{{ pod_ports | default(omit) }}"
    quadlet_filename: "{{ container_pod }}"
    quadlet_file_mode: '0640'
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target    
    
      