---

# Register variable_result variable
- name: Register variable (variable_result)...
  ansible.builtin.set_fact:
    variable_result: ""
  no_log: true
  when: variable_result is not defined

# Clear variable variable_result, be sure it is not used from a previous run.
- name: Clear variable...
  ansible.builtin.set_fact:
    variable_result: ""
  no_log: true

# Get variables from podman role

