---

#########################################################
## Podman Networks administration module               ##
#########################################################

# Validate global variables.
- name: Validate variables for Podman pods module...
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - container_network

#########################################################
## Podman Create Network                               ##
#########################################################

# Create network
- name: Create Podman network...
  when: action == "create_network"
  block:

    # Validate global variables.
    - name: Validate variables for action...
      ansible.builtin.assert:
        that: "varitem is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop:
        - container_repository_url
        - container_name

##################################
# Create podman network quadlet  #
##################################

# Create Podman network to isolate one or more containers in running environment
- name: "Create Podman Network with name {{ container_network }}..."
  become: true
  become_user: "{{ podman_vars.service_user }}"
  containers.podman.podman_network:
    name: "{{ container_network }}"
    state: quadlet

#########################################################
## Podman Destroy Network                              ##
#########################################################

# Destroy network
- name: Destroy Podman network...
  when: action == "destroy_network"
  block:

    # Show information message
    - name: "This part is not (yet) implemented."
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Post-actions                                        ##
#########################################################

# Unset variables
#- name: Unset variables...
#  ansible.builtin.set_fact:
#    <variable>: null