---
- name: Verify
  hosts: all
  tasks:
    - name: Check if Podman is installed
      ansible.builtin.command: podman --version
      register: podman_version
    - name: Assert Podman is installed
      ansible.builtin.assert:
        that:
          - "'podman' in podman_version.stdout"