---

# Create container with quadlet
- name: Create container with quadlet
  hosts: localhost
  vars:
    vault_address: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR', default=Undefined) }}"
    vault_token: "{{ lookup('ansible.builtin.env', 'VAULT_TOKEN', default=Undefined) }}"

  tasks:
# Import container
  - name: "Create container with quadlet"
    ansible.builtin.include_role:
      name: podman
    vars:
      action: import_container
      podman:
        container:
          name: "myregistry"
          repository_url: "docker.io/library/registry"
          repository_tag: "latest"
          ports: "5000:5000"
          quadlet: |
            [Unit]
            Description=Podman Registry
            After=network.target

            [Service]
            Restart=always
            ExecStart=/usr/bin/podman run --name myregistry -p 5000:5000 docker.io/library/registry:latest
            ExecStop=/usr/bin/podman stop myregistry

            [Install]
            WantedBy=multi-user.target    
            